ansible_python_interpreter: "/usr/bin/env python3"

devops_demo_rails_log_to_stdout: true

devops_demo_image_name: "inkovskiy/devops-workshop-app"
devops_demo_nginx_image_name: "inkovskiy/devops-workshop-nginx"
devops_demo_port: 8080
devops_demo_server_name: aws.igor-i.ru
devops_demo_aws_region: eu-central-1b

docker_install_compose: no
docker_package_state: latest
